spring.application.name=agendamento

# Porta onde o servidor vai rodar
server.port=8080

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:1912/barbearia_db
spring.datasource.username=postgres
spring.datasource.password=KARma123@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - como o Java vai conversar com o banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect