spring.application.name=agendamento

# Porta onde o servidor vai rodar
server.port=8080

# Desativa o banco de dados temporariamente (só para testar o servidor)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration